### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by drohen** [StoneCypher/circular_buffer_js#30]
I can do the PR for this when I get a moment, but for some reason types aren't being detected. I believe you will need to reference them in your package.json file under the "types" property.

Nice work anyway, thanks.

**Comment by StoneCypher** [comment]
You are correct.  Fixing now

**Comment by StoneCypher** [comment]
Thank you @drohen

**Comment by drohen** [comment]
@StoneCypher don't forget to build and publish to npm

**Comment by StoneCypher** [comment]
egad.  long day

re-fixed.  tyvm

**Comment by StoneCypher** [comment]
actually this might be a little weird but i might as well ask

i wasn't sure whether to fix this or not.  i couldn't tell if what you would want to see is a high speed responsive maintainer, or if you wanted to participate, and that's why you said you could make the pr

which would have been kinder?

**Comment by drohen** [comment]
less work I have to do on other people's code, the better. I have other stuff to focus on, so I appreciate your speed.
also your humorous attitude is actually what makes it "kinder".
If you do need help with anything specific though, just ask.

**Comment by StoneCypher** [comment]
nah i actually mostly made this repo as a teaching device for a friend of mine :)

you're welcome to contribute if you're interested.  otherwise i'll probably get around to doing more api sooner or later
