### ISSUE TITLE
More suggestion than issue

### ISSUE THREAD

**Issue by drohen** [StoneCypher/circular_buffer_js#48]
To make it closer to the array spec, setting `buffer.length = 0` should be equivalent to calling `buffer.clear()`.

**Comment by StoneCypher** [comment]
Agreed

**Comment by StoneCypher** [comment]
so ... i was thinking about it.

this container has `length` and `capacity`, and they both mean variations on what they do in an array

the problem is that in a javascript array, `.length = 0` also resizes it, because that api was written before holes existed, so back then, they meant the same thing

but on this container they explicitly don't mean that, because there's capacity

how would you feel about my offering a setter on `.capacity` that resizes, and a setter on `.length` that merely empties?  that seems to fit principle of least surprise, ***but it's meaningfully different than what js does***

i don't see a particularly clear solution here tbh other than to rename capacity length, which seems bad

**Comment by drohen** [comment]
Hopefully I understand but maybe you can just write a piece of code to articulate it. I think your idea is sound. Capacity to me I guess is where this structure escapes the array API as setting the capacity to 0 would be "no positions possible" ie not an empty collection so much as a collection of none. As an array is theoretically infinitely sizable, this is the difference, whereas circular buffer does have a hard limit as this is the point. Setting length so a value within the capacity, to a value lesser than what is used would basically "delete" the excess values beyond the position:
`buff.capacity // 5`
`buff.available // 1`
`buff.length = 1`
`buff.available // 4`
`buff.length = 10 // error or no-op or fill buffer with empty or something`

I guess you don't have a resize function so `buff.capacity = x` should probably just error.

**Comment by StoneCypher** [comment]
[i do have a resize function actually](https://github.com/StoneCypher/circular_buffer_js/blob/main/src/ts/circular_buffer.ts#L651)

**Comment by drohen** [comment]
:O

**Comment by drohen** [comment]
Well I guess my last line would just be equating capacity assignment = resize(). In any case, all the above is just my mental model of how I'd assume it would work.

**Comment by StoneCypher** [comment]
I implemented this a while ago, but I got stuck on how to do something in the randomized test library and opened a bug

The author responded promptly but I missed it

[I noticed it last night, implemented it, and pushed it](https://github.com/StoneCypher/circular_buffer_js/commit/0dd5d0f1c73b7752f22367f62e771978625e79c3#diff-3f1963739f20a75fc870aaaa4544554c3a0f9322faa360c33a803289d93b5b66R23)

Your suggestion is live in 1.8.0

Thank you for the contribution, @drohen .  Sorry it took me so long
